### ISSUE TITLE
"Not found" error

### ISSUE THREAD

**Issue by rvanbaalen** [julien-vidal/github-label-manager#2]
I keep getting an error while trying to execute `glm copy company/repo company/other-repo`:

``` sh
$ {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
```

**Comment by julien-vidal** [comment]
This message appear if the repository dosen't exist and if I remember well, it appear when you don't have enough rights on repository too...

Maybe you should check what kind of rights you have with your github token.

Hope this can resolve your problem.

**Comment by zakcrawford** [comment]
I am getting this error as well.

Do you know what permission is required?
I have given the token all permissions and it still fails.
